//
// Generated file, do not edit! Created by opp_msgtool 6.0 from ChordAppMsg.msg.
//

#ifndef __CHORD_CHORDAPPMSG_M_H
#define __CHORD_CHORDAPPMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace chord {

class ChordAppMsg;

}  // namespace chord

// cplusplus {{
#include <vector>
// }}


namespace chord {

/**
 * Enum generated from <tt>ChordAppMsg.msg:7</tt> by opp_msgtool.
 * <pre>
 * enum MsgType
 * {
 *     TASK_MSG = 1;
 *     RESULT_MSG = 2;
 *     GOSSIP_MSG = 3;
 * }
 * </pre>
 */
enum MsgType {
    TASK_MSG = 1,
    RESULT_MSG = 2,
    GOSSIP_MSG = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MsgType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MsgType& e) { int n; b->unpack(n); e = static_cast<MsgType>(n); }

/**
 * Class generated from <tt>ChordAppMsg.msg:13</tt> by opp_msgtool.
 * <pre>
 * message ChordAppMsg
 * {
 *     int msgType \@enum(MsgType) = TASK_MSG;
 * 
 *     // Common routing
 *     int sourceId;
 *     int destId;
 * 
 *     // For TaskMsg
 *     int initiatorId;
 *     int subtaskId;
 *     int data[]; // The array elements (using dynamic array instead of vector)
 * 
 *     // For ResultMsg
 *     int maxResult;
 * 
 *     // For GossipMsg
 *     int gossipOriginIP; // We use node ID as IP (e.g. 192.168.0.x)
 *     double gossipTimestamp;
 *     int gossipClientId;
 * }
 * </pre>
 */
class ChordAppMsg : public ::omnetpp::cMessage
{
  protected:
    int msgType = TASK_MSG;
    int sourceId = 0;
    int destId = 0;
    int initiatorId = 0;
    int subtaskId = 0;
    int *data = nullptr;
    size_t data_arraysize = 0;
    int maxResult = 0;
    int gossipOriginIP = 0;
    double gossipTimestamp = 0;
    int gossipClientId = 0;

  private:
    void copy(const ChordAppMsg& other);

  protected:
    bool operator==(const ChordAppMsg&) = delete;

  public:
    ChordAppMsg(const char *name=nullptr, short kind=0);
    ChordAppMsg(const ChordAppMsg& other);
    virtual ~ChordAppMsg();
    ChordAppMsg& operator=(const ChordAppMsg& other);
    virtual ChordAppMsg *dup() const override {return new ChordAppMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMsgType() const;
    virtual void setMsgType(int msgType);

    virtual int getSourceId() const;
    virtual void setSourceId(int sourceId);

    virtual int getDestId() const;
    virtual void setDestId(int destId);

    virtual int getInitiatorId() const;
    virtual void setInitiatorId(int initiatorId);

    virtual int getSubtaskId() const;
    virtual void setSubtaskId(int subtaskId);

    virtual void setDataArraySize(size_t size);
    virtual size_t getDataArraySize() const;
    virtual int getData(size_t k) const;
    virtual void setData(size_t k, int data);
    virtual void insertData(size_t k, int data);
    [[deprecated]] void insertData(int data) {appendData(data);}
    virtual void appendData(int data);
    virtual void eraseData(size_t k);

    virtual int getMaxResult() const;
    virtual void setMaxResult(int maxResult);

    virtual int getGossipOriginIP() const;
    virtual void setGossipOriginIP(int gossipOriginIP);

    virtual double getGossipTimestamp() const;
    virtual void setGossipTimestamp(double gossipTimestamp);

    virtual int getGossipClientId() const;
    virtual void setGossipClientId(int gossipClientId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ChordAppMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ChordAppMsg& obj) {obj.parsimUnpack(b);}


}  // namespace chord


namespace omnetpp {

template<> inline chord::ChordAppMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<chord::ChordAppMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CHORD_CHORDAPPMSG_M_H

